### ISSUE TITLE
Cross Architecture Use of standards (Please enable git discussions)

### ISSUE THREAD

**Issue by 0Grit** [espressif/svd#15]
Bravo on experimenting with an open standard.

I'd love to see this work evolve into using more of CMSIS and eventually enable CMSIS & RISC-V to also benefit from it.

Are you in contact with anybody from the ARM teams now that they are making the CMSIS packs concept more open?

**Comment by jessebraham** [comment]
I apologize for getting to this issue so late, I have been preoccupied with other projects. Thank you all for your interest!

To answer the initial question, no I have not been in contact with anybody from the ARM team. I am unsure at this point if we will use anything else from CMSIS. We are producing these SVDs largely at the request of the community, and I'm admittedly not well versed with CMSIS in general. I suppose if somebody made a compelling argument for something in particular it could be considered, though.

Discussions are now enabled so please move any further conversation here: https://github.com/espressif/svd/discussions/17
