### ISSUE TITLE
I2S1 missing on esp32

### ISSUE THREAD

**Issue by sepotvin** [espressif/svd#18]
I2S0 is defined as I2S and I2S1 is missing in the esp32 PAC based on the svd for esp32. The same workaround that was created for I2C0 and I2C1 should probably be applied to I2S also.

**Comment by jessebraham** [comment]
Thanks for opening this issue.

I've been having some issues with duplicate definitions when I include `I2S1` and generate the PAC using `svd2rust`, so I have omitted it for the time being. Hopefully in the next release I will have resolved these issues and included the peripheral. I will rename `I2S` to I2S0` when this happens as well.
