### ISSUE TITLE
Registers in ESP32-C3/S3 `RTC_CNTL` peripheral still have prefix

### ISSUE THREAD

**Issue by ducktec** [espressif/svd#20]
In the ESP32-C3 and ESP32-S3 SVD, the registers for the `RTC_CNTL` still have the peripheral prefix, e.g. `RTC_WDTCONFIG0`. For the ESP32 and ESP32-S2, this register is just called `WDTCONFIG0`.

The C3 peripheral is slightly different, so the difference does not matter that much there, but since ESP32/S2/S3 all seem to share the same WDT structure it would be convenient to have them named identically.

**Comment by jessebraham** [comment]
Thanks for pointing this out. Will be fixed in the next version of each SVD.

**Comment by jessebraham** [comment]
The `RTC_` prefixes should all be stripped in the newest SVD for the ESP32-S3.
