### ISSUE TITLE
RMT peripheral missing for ESP32-S3

### ISSUE THREAD

**Issue by ducktec** [espressif/svd#21]
The SVD file for the ESP32-S3 is missing the RMT peripheral.

**Comment by jessebraham** [comment]
Thanks for letting me know. I'll try to hunt down the source file for this peripheral and get a new SVD out as soon as possible.

**Comment by ducktec** [comment]
Thanks a lot! This is a perfect starting point for patching rather than having to start from scratch.

**Comment by jessebraham** [comment]
A new SVD containing the `RMT` peripheral has been pushed to `main`.
