### ISSUE TITLE
Add Releases for SVD files ?

### ISSUE THREAD

**Issue by brianignacio5** [espressif/svd#22]
Could we add resulting SVD as release files ? In this way we could download them from any scripting, IDE, command line tool that wants to work with them.

Also enabling mirrors in Espressif DL servers.

**Comment by aykevl** [comment]
One place where they are stored is here: https://github.com/posborne/cmsis-svd/tree/master/data/Espressif
Probably out of date, but it might be useful.

**Comment by jessebraham** [comment]
Not against doing this but I'm not really sure how to go about accomplishing it. SVDs are updated irregularly (they do not get updated all at once) and the version numbers are not in sync.

**Comment by igrr** [comment]
How about making an automated release whenever something gets updated, using the current YYYYMMDD date as the release tag? Not ideal, but at least it's going to be pretty easy to set up and won't require changes to the project workflow.

**Comment by igrr** [comment]
We could also maintain the "latest" release using https://github.com/eine/tip.
