### ISSUE TITLE
BUS_TIMING_0 register definition for ESP32

### ISSUE THREAD

**Issue by pierremolinaro** [espressif/svd#29]
According to ESP32 TRM (Version 4.7), table 21-6 page 543, I think there is an error in version 13 of `esp32.svd` file for the `BUS_TIMING_0` register definition of `TWAI` module.

The `BAUD_PRESC` field:
             ` <bitOffset>0</bitOffset>`
             ` <bitWidth>6</bitWidth>` instead of 14

The `SYNC_JUMP_WIDTH` field:
             ` <bitOffset>6</bitOffset>`  instead of 14
             `<bitWidth>2</bitWidth>`

Best regards,

Pierre

**Comment by jessebraham** [comment]
Thanks for opening this issue. These fields have been corrected in version 14 of the SVD.
